name: Python Lint Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4

    - name: Set up Python
      run: |
        sudo apt update -y; 
        sudo apt upgrade -y; 
        sudo apt install software-properties-common -y; 
        sudo add-apt-repository ppa:deadsnakes/ppa -y ;
        sudo apt update -y ; sudo apt install python3.13 -y
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Create directory for Pylint report
      run: mkdir -p post_traces

    - name: Run Pylint and save report
      run: pylint ./*.py > post_traces/pylint_report.txt || true

    - name: Upload Pylint report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report
        path: post_traces/pylint_report.txt
