name: Python Type Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  type_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      run: |
        sudo apt update -y; 
        sudo apt upgrade -y; 
        sudo apt install software-properties-common -y; 
        sudo add-apt-repository ppa:deadsnakes/ppa -y;
        sudo apt update -y; 
        sudo apt install python3.13 -y

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyright
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Pyright and save report
      run: |
        pyright > post_traces/pyright_report.txt
        cat post_traces/pyright_report.txt
